### PR TITLE
Fix segfault on nightly for `nvim_buf_get_lines()` and `nvim_buf_get_text()`

### LINKED ISSUE #92: Segmentation fault on `nvim-0.9` when using `Buffer.get_lines()`
I recently updated my neovim nightly version, everything seem to work except using `Buffer.get_lines()` segfaults w/:

2022-12-14-175341_538x108_scrot

Here's a minimal code from `api` example that reproduces the error:
```rs
use nvim_oxi::api::{self, opts::*, types::*, Buffer};
use nvim_oxi::{self as oxi};

#[oxi::module]
fn api() -> oxi::Result<()> {
    // Create a new `Greetings` command.
    let opts = CreateCommandOpts::builder()
        .bang(true)
        .desc("shows a greetings message")
        .nargs(CommandNArgs::ZeroOrOne)
        .build();

    let greetings = |args: CommandArgs| {
        let who = args.args.unwrap_or("from Rust".to_owned());
        let bang = if args.bang { "!" } else { "" };
        print!("Hello {}{}", who, bang);
        Ok(())
    };

    api::create_user_command("Greetings", greetings, &opts)?;

    // Remaps `hi` to `hello` in insert mode.
    api::set_keymap(Mode::Insert, "hi", "hello", &Default::default())?;

    // This line segfaults
    let _ = Buffer::current().get_lines(1..10, true)?;

    Ok(())
}
```
```toml
# Cargo.toml
[dependencies]
nvim-oxi = { version = "0.2.2", features = ["neovim-nightly"]  }
```

nvim-oxi version: `0.2.2`

Neovim version that segfaults:
```
NVIM v0.9.0-dev-506+g090048bec
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az246-948

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Neovim version that works:
```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az178-366

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

OS:
```

        /\         krivah@arch
       /  \        OS:        Arch Linux
      /\   \       KERNEL:    Linux 5.15.80-1-lts
     /  __  \      UPTIME:    13 hours, 43 minutes
    /  (  )  \     PACKAGES:  2034
   / __|  |__\\    SHELL:     zsh
  /.`        `.\   WM:        bspwm
```

### PR DESCRIPTION
**Pull request by calops**
https://github.com/neovim/neovim/pull/19877 introduced breaking changes for the `nvim_buf_get_lines()` and `nvim_buf_get_text()` functions, adding a `luaState` argument. This PR passes `NULL` for that argument, as it seems safe to do (it will simply allocate on its own if no lua state is present).

Fixes #92

### CODE REVIEW

File: crates/nvim-api/src/buffer.rs [hunk 1]
```diff
@@ -314,6 +309,8 @@ impl Buffer {
                 start,
                 end,
                 strict_indexing,
+                #[cfg(feature = "neovim-nightly")]
+                std::ptr::null_mut(),
```
Comment (noib3) [inline crates/nvim-api/src/buffer.rs:313]: We can just use the initialized Lua state:

```rust
#[cfg(feature = "neovim-nightly")]
luajit_bindings::with_state(|lstate| lstate),
```

File: crates/nvim-api/src/buffer.rs [hunk 2]
```diff
@@ -407,6 +404,8 @@ impl Buffer {
                 end,
                 end_col.try_into()?,
                 opts.non_owning(),
+                #[cfg(feature = "neovim-nightly")]
+                std::ptr::null_mut(),
```
Comment (noib3) [inline crates/nvim-api/src/buffer.rs:408]: same as above

File: crates/nvim-api/src/ffi/buffer.rs [hunk 3]
```diff
@@ -1,19 +1,13 @@
+#[cfg(feature = "neovim-nightly")]
+use luajit_bindings as lua;
```
Comment (noib3) [inline crates/nvim-api/src/ffi/buffer.rs:2]: nit: not a fan of `cfg`-specific use statements, can you use the more verbose `*mut luajit_bindings::ffi::lua_State` instead?

**Review by noib3 — CHANGES_REQUESTED** [review]
Good catch! We can merge this after the comments get addressed. Can you also run `cargo fmt` on those commits? There are a few formatting changes unrelated to the MR.

File: crates/nvim-api/src/buffer.rs (hunk 1 above)
Comment (calops) [reply crates/nvim-api/src/buffer.rs:313]: What's what I tried at first, but for some unknown reason, this makes `nvim_buf_get_text()` return *zero* lines instead. I have no idea how to go about debugging that, but anything but a null pointer here breaks the function. Same with `get_lines()`.

I should have mentioned that in the PR, but as a stop-gap measure the null pointer should be good enough until we figure out what's happening (it matches the behavior the function had before the changes in neovim).

File: crates/nvim-api/src/buffer.rs (hunk 2 above)
Comment (calops) [reply crates/nvim-api/src/buffer.rs:408]: same as above

**Comment by calops** [comment]
> Can you also run cargo fmt on those commits? There are a few formatting changes unrelated to the MR.

I'm confused about this. The changes you mention *are* the output of `rustfmt` for me. In fact, running `cargo fmt` on the project makes a whole bunch of similar changes across the whole project. I have no idea what's going on if this is not the expected behavior. Is there a system-wide rustfmt config file that could be interfering on my setup? I've already checked and `~/.config/rustfmt` doesn't exist for me.

File: crates/nvim-api/src/buffer.rs (hunk 1 above)
Comment (noib3) [reply crates/nvim-api/src/buffer.rs:313]: Sounds good. Can you mention this in both `Buffer::get_text()` and `Buffer::get_lines()` so that we know why we're using null pointers there?

**Comment by noib3** [comment]
Ah my bad, I should've mentioned that we're using [unstable formatting features](https://github.com/noib3/nvim-oxi/blob/master/rustfmt.toml#L7), so the formatter must be run using a nightly version of Rust. Since the changes are small you could probably fix them manually.

**Comment by noib3** [comment]
One last nit: b0e29d294d521556b250c3de60e8145c33a50fe2 should be squashed on the first commit.

**Comment by calops** [comment]
All the comments should have been addressed now.
